"""
Natuurpunt Agenda Agent
=======================
A REAL agent: you run it, and Claude figures out by itself how to
scrape the Natuurpunt agenda, extract Vlaams-Brabant events, and
generate a calendar file. You don't write any scraping code — the
agent inspects the page, reasons about the HTML structure, writes
Python code to parse it, executes that code, and gives you the .ics.

Usage:
    pip install anthropic requests beautifulsoup4 icalendar
    export ANTHROPIC_API_KEY="your-key-here"
    python natuurpunt_agent.py

Optional (if the page needs JavaScript):
    pip install selenium
"""

import json
import os
import sys
import traceback
from pathlib import Path

import requests
from anthropic import Anthropic

client = Anthropic()
MODEL = "claude-sonnet-4-20250514"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "nl-BE,nl;q=0.9,en;q=0.8",
}

NOTES_FILE = Path("agent_notes.json")


def load_notes() -> dict:
    """Load the agent's memory from previous runs."""
    if NOTES_FILE.exists():
        try:
            return json.loads(NOTES_FILE.read_text())
        except (json.JSONDecodeError, IOError):
            return {}
    return {}


def save_notes(notes: str) -> dict:
    """
    Save notes for future runs. Claude calls this to remember what worked.
    Notes are appended to a list with a timestamp.
    """
    from datetime import datetime

    memory = load_notes()
    if "entries" not in memory:
        memory["entries"] = []

    memory["entries"].append({
        "timestamp": datetime.now().isoformat(),
        "notes": notes,
    })

    # Keep only the last 10 entries to avoid bloat
    memory["entries"] = memory["entries"][-10:]

    NOTES_FILE.write_text(json.dumps(memory, indent=2, ensure_ascii=False))
    return {"success": True, "total_entries": len(memory["entries"])}


def save_working_script(code: str) -> dict:
    """
    Save the working Python code as a standalone script.
    This script can be run directly without the agent or API key.
    """
    script_path = Path("scrape_natuurpunt.py")
    header = '''"""
Natuurpunt Vlaams-Brabant — Standalone Scraper
================================================
Auto-generated by the agent. Run this directly to update the calendar
without needing the Anthropic API.

Usage:
    source venv/bin/activate
    python scrape_natuurpunt.py
"""

'''
    script_path.write_text(header + code, encoding="utf-8")
    return {"success": True, "path": str(script_path.resolve())}


# ── Tools the agent can use ─────────────────────────────────────────────────

def fetch_url(url: str) -> dict:
    """Fetch a URL and return the HTML content."""
    try:
        resp = requests.get(url, headers=HEADERS, timeout=20)
        resp.raise_for_status()
        html = resp.text
        if len(html) > 80_000:
            html = html[:80_000] + "\n\n... [TRUNCATED — page was very long] ..."
        return {"status": resp.status_code, "length": len(resp.text), "html": html}
    except requests.RequestException as e:
        return {"error": str(e)}


def fetch_url_selenium(url: str) -> dict:
    """Fetch a URL using Selenium (for JavaScript-rendered pages)."""
    try:
        from selenium import webdriver
        from selenium.webdriver.chrome.options import Options
        from selenium.webdriver.support.ui import WebDriverWait
        from selenium.webdriver.support import expected_conditions as EC
        from selenium.webdriver.common.by import By
    except ImportError:
        return {"error": "Selenium is not installed. Install with: pip install selenium"}

    try:
        options = Options()
        options.add_argument("--headless")
        options.add_argument("--no-sandbox")
        options.add_argument("--disable-dev-shm-usage")
        driver = webdriver.Chrome(options=options)
        driver.get(url)

        try:
            WebDriverWait(driver, 10).until(
                EC.presence_of_element_located(
                    (By.CSS_SELECTOR, "article, .views-row, .view-content, .agenda-item")
                )
            )
        except Exception:
            pass

        import time
        time.sleep(2)

        html = driver.page_source
        driver.quit()

        if len(html) > 80_000:
            html = html[:80_000] + "\n\n... [TRUNCATED] ..."
        return {"status": 200, "length": len(html), "html": html}
    except Exception as e:
        return {"error": str(e)}


def run_python_code(code: str) -> dict:
    """Execute Python code and return the output."""
    exec_globals = {"__builtins__": __builtins__}

    import io
    from contextlib import redirect_stdout, redirect_stderr

    stdout_capture = io.StringIO()
    stderr_capture = io.StringIO()

    try:
        with redirect_stdout(stdout_capture), redirect_stderr(stderr_capture):
            exec(code, exec_globals)

        result = {"success": True, "stdout": stdout_capture.getvalue()}
        stderr_text = stderr_capture.getvalue()
        if stderr_text:
            result["stderr"] = stderr_text

        ics_path = Path("natuurpunt_vlaams_brabant.ics")
        if ics_path.exists():
            result["ics_file_created"] = True
            result["ics_file_size"] = ics_path.stat().st_size
            content = ics_path.read_text(errors="replace")
            result["event_count"] = content.count("BEGIN:VEVENT")

        return result

    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc(),
            "stdout": stdout_capture.getvalue(),
        }


# ── Tool definitions for Claude ─────────────────────────────────────────────

TOOLS = [
    {
        "name": "fetch_url",
        "description": (
            "Fetch a web page by URL using requests. Returns the HTML content. "
            "Use this to inspect the Natuurpunt agenda page structure. "
            "The HTML will be truncated if very long."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "url": {"type": "string", "description": "The URL to fetch"}
            },
            "required": ["url"],
        },
    },
    {
        "name": "fetch_url_selenium",
        "description": (
            "Fetch a web page using Selenium with a headless Chrome browser. "
            "Use this if fetch_url returns a page with no event content "
            "(the page might require JavaScript to render). "
            "Returns the fully rendered HTML."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "url": {"type": "string", "description": "The URL to fetch with Selenium"}
            },
            "required": ["url"],
        },
    },
    {
        "name": "run_python_code",
        "description": (
            "Execute Python code to parse HTML, extract events, and generate "
            "an .ics calendar file. The code runs in a fresh Python environment "
            "with access to all standard libraries plus: requests, bs4 "
            "(BeautifulSoup), icalendar, re, json, datetime, hashlib, pathlib. "
            "The code should save the calendar to 'natuurpunt_vlaams_brabant.ics'. "
            "Write complete, self-contained code (including all imports)."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "code": {"type": "string", "description": "The Python code to execute"}
            },
            "required": ["code"],
        },
    },
    {
        "name": "save_notes",
        "description": (
            "Save notes about what worked for future runs. Call this at the end "
            "of a successful run to record: which URL worked, which CSS selectors "
            "found the events, what date format was used, what code patterns worked, "
            "and any other useful observations. These notes will be loaded "
            "automatically on the next run so you can skip the exploration phase."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "notes": {
                    "type": "string",
                    "description": (
                        "Free-text notes about what worked. Include: working URLs, "
                        "CSS selectors, date formats found, pagination approach, "
                        "and the final working Python code or key snippets."
                    ),
                }
            },
            "required": ["notes"],
        },
    },
    {
        "name": "save_working_script",
        "description": (
            "Save the final working Python code as a standalone script called "
            "'scrape_natuurpunt.py'. This script can be run directly with "
            "'python scrape_natuurpunt.py' without needing the agent or an API key. "
            "ALWAYS call this after a successful run. Pass the exact same code that "
            "successfully generated the .ics file. The user's cron job will run this "
            "standalone script instead of the full agent."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "description": "The complete, self-contained Python code that successfully generated the .ics file",
                }
            },
            "required": ["code"],
        },
    },
]

TOOL_FUNCTIONS = {
    "fetch_url": lambda **kwargs: fetch_url(**kwargs),
    "fetch_url_selenium": lambda **kwargs: fetch_url_selenium(**kwargs),
    "run_python_code": lambda **kwargs: run_python_code(**kwargs),
    "save_notes": lambda **kwargs: save_notes(**kwargs),
    "save_working_script": lambda **kwargs: save_working_script(**kwargs),
}


# ── System prompt ────────────────────────────────────────────────────────────

def build_system_prompt() -> str:
    """Build the system prompt, injecting saved notes from previous runs."""
    base = """\
You are an autonomous web scraping agent. Your task is to:

1. Fetch the Natuurpunt agenda page (https://www.natuurpunt.be/agenda)
2. Inspect the HTML to understand the page structure
3. Figure out how to filter or find events for the province "Vlaams-Brabant"
4. Write and execute Python code that:
   - Parses the events (title, date, time, location, description, URL)
   - Filters for Vlaams-Brabant events. They can be found under this URL: \
https://www.natuurpunt.be/agenda?f%5B0%5D=province%3A187
   - Add event information to an .ics calendar file using the icalendar \
library. I'd basically like to see the information from the website in \
calendar form, so I can import it into Google Calendar or Apple Calendar. \
The calendar should be timezone-aware (Europe/Brussels) and handle Dutch \
date formats.
   - Generates an .ics calendar file saved as 'natuurpunt_vlaams_brabant.ics'

Strategy:
- If you have notes from previous runs (see below), USE THEM to skip \
the exploration phase and go straight to writing code that worked before. \
Only re-explore if the saved approach fails.
- If no notes exist, start by fetching the Vlaams-Brabant filtered agenda \
page to see the HTML structure: \
https://www.natuurpunt.be/agenda?f%5B0%5D=province%3A187
- If the page is JavaScript-rendered (fetch_url returns empty/minimal \
content), try fetch_url_selenium
- Once you understand the HTML structure, write Python code to parse it \
and generate the .ics file
- The code you write should also handle pagination if there are multiple \
pages of events
- Handle Dutch date formats (e.g., "za 12 april 2025", "12/04/2025")
- Set timezone to Europe/Brussels
- If your code fails, read the error and fix it

IMPORTANT: After successfully generating the .ics file, ALWAYS call \
save_notes to record what worked:
- The URL(s) that returned event data
- The CSS selectors or HTML patterns used to find events
- The date format(s) encountered
- The working Python code (or at least the key parsing logic)
- Any pagination details
This way the next run can skip exploration and go straight to scraping.

ALSO IMPORTANT: After a successful run, ALWAYS call save_working_script \
with the exact Python code that worked. This saves it as a standalone \
script (scrape_natuurpunt.py) that can be run directly without the agent \
or an API key. The user will use this for scheduled updates.

Be resourceful. If one approach doesn't work, try another.
Print progress to stdout so the user can see what's happening.
"""

    # Load and inject notes from previous runs
    notes = load_notes()
    if notes.get("entries"):
        base += "\n\n--- NOTES FROM PREVIOUS RUNS ---\n"
        base += "Use these to skip exploration and go straight to working code:\n\n"
        for entry in notes["entries"]:
            base += f"[{entry['timestamp']}]\n{entry['notes']}\n\n"
        base += "--- END NOTES ---\n"
        base += "\nIf the website structure hasn't changed, reuse the approach above directly.\n"

    return base


# ── Agentic loop ─────────────────────────────────────────────────────────────

def run_agent():
    print("=" * 60)
    print("\U0001f33f Natuurpunt Vlaams-Brabant Agenda Agent")
    print("=" * 60)
    print()

    # Load memory from previous runs
    notes = load_notes()
    if notes.get("entries"):
        print(f"\U0001f9e0 Loaded {len(notes['entries'])} note(s) from previous runs")
        print(f"   Last run: {notes['entries'][-1]['timestamp']}")
    else:
        print("\U0001f195 First run — agent will explore the website from scratch")

    print()
    print("The agent will now autonomously:")
    print("  1. Fetch the Natuurpunt website")
    print("  2. Figure out the HTML structure")
    print("  3. Extract Vlaams-Brabant events")
    print("  4. Generate an .ics calendar file")
    print()
    print("Sit back and watch it work...\n")

    system_prompt = build_system_prompt()

    messages = [
        {
            "role": "user",
            "content": (
                "Please fetch the Natuurpunt agenda for Vlaams-Brabant, figure out "
                "the page structure, extract upcoming events, and generate an .ics "
                "calendar file I can import into Google Calendar or Apple Calendar. "
                "Save it as 'natuurpunt_vlaams_brabant.ics'. Go!"
            ),
        }
    ]

    loop_count = 0
    max_loops = 20

    while loop_count < max_loops:
        loop_count += 1
        print(f"--- Agent step {loop_count}/{max_loops} ---")

        response = client.messages.create(
            model=MODEL,
            max_tokens=4096,
            system=system_prompt,
            tools=TOOLS,
            messages=messages,
        )

        # ── Display Claude's thinking and tool calls ─────────────────────
        for block in response.content:
            if block.type == "text":
                text = block.text.strip()
                if text:
                    for line in text.split("\n"):
                        print(f"  \U0001f916 {line}")

            elif block.type == "tool_use":
                tool_name = block.name
                tool_input = block.input

                if tool_name == "run_python_code":
                    code = tool_input.get("code", "")
                    print(f"\n  \U0001f527 Running Python code ({len(code)} chars)...")
                elif tool_name == "fetch_url":
                    print(f"\n  \U0001f310 Fetching: {tool_input.get('url', '?')}")
                elif tool_name == "fetch_url_selenium":
                    print(f"\n  \U0001f310 Fetching (Selenium): {tool_input.get('url', '?')}")
                elif tool_name == "save_notes":
                    print(f"\n  \U0001f9e0 Saving notes for next run...")
                elif tool_name == "save_working_script":
                    print(f"\n  \U0001f4be Saving standalone script...")
                else:
                    print(f"\n  \U0001f527 Tool call: {tool_name}")

        # ── If done, show results and exit ───────────────────────────────
        if response.stop_reason == "end_turn":
            print(f"\n\u2705 Agent finished in {loop_count} steps.")

            ics_path = Path("natuurpunt_vlaams_brabant.ics")
            if ics_path.exists():
                size = ics_path.stat().st_size
                content = ics_path.read_text(errors="replace")
                event_count = content.count("BEGIN:VEVENT")
                print(f"\n\U0001f4c5 Calendar file: {ics_path.resolve()}")
                print(f"   Size: {size:,} bytes")
                print(f"   Events: {event_count}")
                print(f"\n   To import:")
                print(f"   \u2022 macOS: Double-click the .ics file")
                print(f"   \u2022 Google Calendar: Settings \u2192 Import & Export \u2192 Import")
            else:
                print("\n\u26a0\ufe0f  No .ics file was generated.")
            return

        # ── Execute tool calls and feed results back ─────────────────────
        if response.stop_reason == "tool_use":
            messages.append({"role": "assistant", "content": response.content})

            tool_results = []
            for block in response.content:
                if block.type == "tool_use":
                    # Robust tool execution with error handling
                    try:
                        if block.name in TOOL_FUNCTIONS:
                            func = TOOL_FUNCTIONS[block.name]
                            result = func(**block.input)
                        else:
                            result = {"error": f"Unknown tool: {block.name}"}
                    except TypeError as e:
                        result = {
                            "error": f"Bad parameters for {block.name}: {e}",
                            "input_received": str(block.input)[:200],
                        }
                    except Exception as e:
                        result = {"error": f"Tool execution failed: {e}"}

                    # Print a summary of the result
                    if block.name in ("fetch_url", "fetch_url_selenium"):
                        if "error" in result:
                            print(f"  \u274c {result['error']}")
                        else:
                            print(f"  \u2705 Got {result['length']:,} bytes (status {result['status']})")
                    elif block.name == "run_python_code":
                        if result.get("success"):
                            stdout = result.get("stdout", "").strip()
                            if stdout:
                                for line in stdout.split("\n")[:15]:
                                    print(f"     {line}")
                                if stdout.count("\n") > 15:
                                    print(f"     ... ({stdout.count(chr(10)) - 15} more lines)")
                            if result.get("ics_file_created"):
                                print(f"  \U0001f4c4 .ics file created! ({result['event_count']} events)")
                        else:
                            print(f"  \u274c Code error: {result.get('error', '?')}")
                            tb = result.get("traceback", "")
                            if tb:
                                for line in tb.strip().split("\n")[-5:]:
                                    print(f"     {line}")
                    elif block.name == "save_notes":
                        if result.get("success"):
                            print(f"  \u2705 Notes saved! ({result['total_entries']} total entries in memory)")
                        else:
                            print(f"  \u274c Failed to save notes: {result.get('error', '?')}")
                    elif block.name == "save_working_script":
                        if result.get("success"):
                            print(f"  \u2705 Standalone script saved: {result['path']}")
                            print(f"     Run it directly: python scrape_natuurpunt.py")
                        else:
                            print(f"  \u274c Failed to save script: {result.get('error', '?')}")
                    else:
                        print(f"  Result: {str(result)[:200]}")

                    tool_results.append({
                        "type": "tool_result",
                        "tool_use_id": block.id,
                        "content": json.dumps(result, default=str)[:15000],
                    })

            messages.append({"role": "user", "content": tool_results})

    print("\n\u26a0\ufe0f  Agent hit the maximum step limit. It may not have finished.")


# ── Entry point ──────────────────────────────────────────────────────────────

if __name__ == "__main__":
    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("\u274c Please set your ANTHROPIC_API_KEY environment variable:")
        print("   export ANTHROPIC_API_KEY='sk-ant-...'")
        sys.exit(1)

    run_agent()