"""
Natuurpunt Vlaams-Brabant — Standalone Scraper
================================================
Auto-generated by the agent. Run this directly to update the calendar
without needing the Anthropic API.

Usage:
    source venv/bin/activate
    python scrape_natuurpunt.py
"""

#!/usr/bin/env python3
"""
Standalone script to scrape Natuurpunt Vlaams-Brabant events and generate an .ics calendar file.
This script can be run directly with: python scrape_natuurpunt.py
"""

import requests
from bs4 import BeautifulSoup
from icalendar import Calendar, Event
import pytz
from datetime import datetime, timedelta
import re
import hashlib
import os
import time
import random

def scrape_natuurpunt_vlaams_brabant():
    print("Starting Natuurpunt Vlaams-Brabant agenda scraping with rate limiting...")

    # Initialize calendar
    cal = Calendar()
    cal.add('prodid', '-//Natuurpunt Vlaams-Brabant Events//natuurpunt.be//')
    cal.add('version', '2.0')
    cal.add('calscale', 'GREGORIAN')
    cal.add('method', 'PUBLISH')
    cal.add('x-wr-calname', 'Natuurpunt Vlaams-Brabant')
    cal.add('x-wr-caldesc', 'Events from Natuurpunt in Vlaams-Brabant province')

    # Set timezone
    tz = pytz.timezone('Europe/Brussels')
    now = datetime.now(tz)

    events_found = {}  # Use dict to remove duplicates by href
    total_pages_checked = 0
    empty_page_count = 0
    max_empty_pages = 3

    print(f"Current time: {now.strftime('%Y-%m-%d %H:%M:%S %Z')}")

    # Base URL pattern for Vlaams-Brabant with pagination
    base_url = "https://www.natuurpunt.be/agenda?f%5B0%5D=province%3A187&page={}"

    # Check pages 0-19 (as found in previous runs)
    for page_num in range(20):
        if empty_page_count >= max_empty_pages:
            print(f"Found {max_empty_pages} consecutive empty pages, stopping pagination")
            break
            
        url = base_url.format(page_num)
        print(f"\nFetching page {page_num}: {url}")
        
        try:
            response = requests.get(url, timeout=30)
            response.raise_for_status()
            soup = BeautifulSoup(response.content, 'html.parser')
            
            # Find event links with date parameters
            event_links = soup.find_all('a', href=re.compile(r'/agenda/[^?]+\?date=\d{2}/\d{2}/\d{4}'))
            
            if not event_links:
                empty_page_count += 1
                print(f"No events found on page {page_num} (empty page count: {empty_page_count})")
                continue
            else:
                empty_page_count = 0  # Reset counter when we find events
            
            print(f"Found {len(event_links)} events on page {page_num}")
            
            for link in event_links:
                href = link.get('href')
                if not href:
                    continue
                    
                # Skip if we've already processed this event
                if href in events_found:
                    continue
                    
                # Extract date from URL parameter
                date_match = re.search(r'date=(\d{2})/(\d{2})/(\d{4})', href)
                if not date_match:
                    continue
                    
                day, month, year = date_match.groups()
                try:
                    event_date = datetime(int(year), int(month), int(day))
                    event_date = tz.localize(event_date.replace(hour=10, minute=0))  # Default time
                except ValueError:
                    print(f"Invalid date format: {day}/{month}/{year}")
                    continue
                
                # Skip past events
                if event_date.date() < now.date():
                    print(f"Skipping past event: {event_date.date()}")
                    continue
                
                # Extract title
                title = link.get_text(strip=True)
                if not title:
                    continue
                    
                # Clean up title
                title = re.sub(r'\s+', ' ', title).strip()
                
                # Build full URL
                if href.startswith('/'):
                    full_url = 'https://www.natuurpunt.be' + href
                else:
                    full_url = href
                
                events_found[href] = {
                    'title': title,
                    'date': event_date,
                    'url': full_url,
                    'location': 'Vlaams-Brabant'
                }
            
            total_pages_checked += 1
            
            # Add small delay between pages
            time.sleep(0.5)
            
        except Exception as e:
            print(f"Error fetching page {page_num}: {e}")
            continue

    print(f"\nFound {len(events_found)} unique events across {total_pages_checked} pages")

    # Time extraction patterns
    time_patterns = [
        r'(\d{1,2}):(\d{2})\s*tot\s*(\d{1,2}):(\d{2})',  # 14:00 tot 17:00
        r'(\d{1,2})\.(\d{2})\s*tot\s*(\d{1,2})\.(\d{2})',  # 14.00 tot 17.00
        r'(\d{1,2}):(\d{2})',  # 14:00
        r'(\d{1,2})\.(\d{2})'   # 14.00
    ]

    # Process a subset of events to avoid rate limiting - fetch only first 50 event pages for time info
    print(f"\nFetching individual event pages for time information (limiting to first 50 to avoid rate limits)...")
    processed_count = 0
    max_detail_fetches = 50

    for href, event_data in list(events_found.items())[:max_detail_fetches]:
        processed_count += 1
        print(f"Processing event {processed_count}/{max_detail_fetches}: {event_data['title'][:50]}...")
        
        try:
            # Add random delay to avoid rate limiting
            time.sleep(random.uniform(0.5, 1.5))
            
            response = requests.get(event_data['url'], timeout=10)
            response.raise_for_status()
            event_soup = BeautifulSoup(response.content, 'html.parser')
            
            # Look for time information in the event page
            page_text = event_soup.get_text()
            
            start_time = None
            end_time = None
            
            for pattern in time_patterns:
                matches = re.findall(pattern, page_text)
                if matches:
                    if len(matches[0]) == 4:  # Start and end time
                        start_hour, start_min, end_hour, end_min = matches[0]
                        start_time = (int(start_hour), int(start_min))
                        end_time = (int(end_hour), int(end_min))
                    elif len(matches[0]) == 2:  # Just start time
                        start_hour, start_min = matches[0]
                        start_time = (int(start_hour), int(start_min))
                    break
            
            # Update event time
            event_date = event_data['date']
            if start_time:
                event_date = event_date.replace(hour=start_time[0], minute=start_time[1])
            
            event_data['date'] = event_date
            
            # Set end time
            if end_time:
                event_end = event_date.replace(hour=end_time[0], minute=end_time[1])
            else:
                # Default 3-hour duration
                event_end = event_date + timedelta(hours=3)
            
            event_data['end_date'] = event_end
            
        except requests.exceptions.RequestException as e:
            if "429" in str(e):
                print(f"Rate limit hit for {event_data['title'][:30]}..., using defaults")
            else:
                print(f"Error fetching event details for {event_data['title'][:30]}...: {e}")
            # Use default end time (3 hours after start)
            event_data['end_date'] = event_data['date'] + timedelta(hours=3)
        except Exception as e:
            print(f"Unexpected error for {event_data['title'][:30]}...: {e}")
            event_data['end_date'] = event_data['date'] + timedelta(hours=3)

    # For remaining events, just use default times
    print(f"\nUsing default times for remaining {len(events_found) - max_detail_fetches} events...")
    for href, event_data in list(events_found.items())[max_detail_fetches:]:
        if 'end_date' not in event_data:
            event_data['end_date'] = event_data['date'] + timedelta(hours=3)

    # Sort events by date
    sorted_events = sorted(events_found.items(), key=lambda x: x[1]['date'])

    print(f"\nGenerating calendar with {len(sorted_events)} events...")

    # Create calendar events
    for href, event_data in sorted_events:
        event = Event()
        event.add('summary', event_data['title'])
        event.add('dtstart', event_data['date'])
        event.add('dtend', event_data['end_date'])
        event.add('location', event_data['location'])
        event.add('description', f"Event details: {event_data['url']}")
        event.add('url', event_data['url'])
        
        # Generate unique UID
        uid_string = f"{event_data['title']}{event_data['date'].isoformat()}{event_data['location']}"
        uid = hashlib.md5(uid_string.encode('utf-8')).hexdigest()
        event.add('uid', f"{uid}@natuurpunt.be")
        
        # Add timestamps
        event.add('dtstamp', now)
        event.add('created', now)
        event.add('last-modified', now)
        
        cal.add_component(event)

    # Save calendar to file
    filename = 'natuurpunt_vlaams_brabant.ics'
    with open(filename, 'wb') as f:
        f.write(cal.to_ical())

    # Check file size and content
    file_size = os.path.getsize(filename)
    print(f"\nCalendar saved to '{filename}' ({file_size/1024:.1f} KB)")

    if sorted_events:
        first_event = sorted_events[0][1]
        last_event = sorted_events[-1][1]
        print(f"Events span from {first_event['date'].strftime('%Y-%m-%d')} to {last_event['date'].strftime('%Y-%m-%d')}")

    print(f"Total unique events: {len(sorted_events)}")
    print(f"Events with detailed time info: {max_detail_fetches}")
    print(f"Events with default time (10:00 AM): {len(sorted_events) - max_detail_fetches}")
    print("Calendar generation complete!")

    return filename, len(sorted_events)

if __name__ == "__main__":
    try:
        filename, event_count = scrape_natuurpunt_vlaams_brabant()
        print(f"\n✅ Successfully generated {filename} with {event_count} events!")
    except Exception as e:
        print(f"❌ Error: {e}")
        exit(1)